name: product_list
description: A Flutter app to display products in a list.

publish_to: 'none' # Remove this line if you plan to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0 # Para birimi formatlaması için eklenmiştir.

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
